### ISSUE TITLE
Provide internationalization support

### ISSUE THREAD

**Issue by felipemarinho97** [felipemarinho97/iskra-webkit-greeter#11]
Some strings is this project (7 to be exact) are written in portuguease.

- [x] Setup i18n support for react
- [x] Provide english translation
- [x] Detect the user language using the _lightdm API_ and try to match the available languages

After that, everyone will can translate this app!

LightDM JS api: https://doclets.io/Antergos/lightdm-webkit2-greeter/master#dl-LightDM-Greeter-language

PRs are welcome

**Comment by frewinchristopher** [comment]
I can snag this! I've added yahoo's `react-intl` to a pre-existing react app before!

**Comment by felipemarinho97** [comment]
Ok! if you want any help about the LightDM API, you can ask me at any time.

**Comment by frewinchristopher** [comment]
The API says that 'language' is a 'member' kind, so I tried accessing it in the components with `window.lightdm.language`, but it's undefined. I see that the functions are called like `window.lightdm.authenticate()`, but am I missing something with these 'member' kinds?

**Comment by felipemarinho97** [comment]
The API only works at run time when the theme is installed.. when developing, you have to use _mock data_. I've mocked some methods on `src/js/mock2.js`, and there are more examples in `src/js/mock.js` that may be useful.

The method `window.lightdm.language` returns the language name: `English`. 
And `window.lightdm.languages` an array of Language like these `{
			name: 'English',
			code: 'en_US.utf8',
			territory: 'USA'
		},
		{
			name: 'Catalan',
			code: 'ca_ES.utf8',
			territory: 'Spain'
},`

**Comment by frewinchristopher** [comment]
Ok, great! I'll take a look.

**Comment by felipemarinho97** [comment]
fixed by #15
