### ISSUE TITLE
Show a warning then inputs are empty

### ISSUE THREAD

**Issue by felipemarinho97** [felipemarinho97/iskra-webkit-greeter#7]
**Current:** Empty inputs are allowed
**Expected:** Don't allow empty strings and show a proper warning

**Comment by bramleyjl** [comment]
I'll take a look at this. Is there something specific you'd like the warning to say? I was thinking "Please enter your username/password."

**Comment by felipemarinho97** [comment]
Yes, these warnings are fine.

Warnings are supported by the *Form* component from Ant Design, and can be done like these:
https://ant.design/components/form/#components-form-demo-register

API: https://ant.design/components/form/
